server:
	g++ server.cpp -o server && g++ client.cpp -o client
# 关于 makefile 和 make ：https://zhuanlan.zhihu.com/p/92010728
#
# 另外发生了一件很无语的事情，我在云端删除了一个文件导致云端与本地节点的版本冲突。
# 然后我在 git push 操作后发现失败，开始还以为是 Makefile 文件的原因，后来才发现需要 git pull 使得云端与本地节点一致才可以。
