server: util.cpp server.cpp Epoll.cpp InetAddress.cpp Socket.cpp client.cpp
	g++ -std=c++11 util.cpp server.cpp Epoll.cpp InetAddress.cpp Socket.cpp -o server
	g++ -std=c++11 util.cpp client.cpp -o client
clean:
	rm server && rm client
